# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0004_contest_contest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('solved', models.IntegerField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.User')),
            ],
        ),
    ]
