# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20151229_1419'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='year',
        ),
        migrations.AddField(
            model_name='userresult',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Participation'),
        ),
    ]
