# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20151229_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='user',
        ),
    ]
