# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_remove_userresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
