# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doreshka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresult',
            options={'ordering': ['-average_time']},
        ),
    ]
