# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreshka', '0002_auto_20160101_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='rj',
            field=models.IntegerField(null=True),
        ),
    ]
