# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doreshka', '0004_userresult_pf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='lg',
            field=models.IntegerField(null=True),
        ),
    ]
