# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doreshka', '0004_userresult_pf'),
        ('doreshka', '0002_auto_20160102_0958'),
    ]

    operations = [
    ]
