# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=30)),
                ('lang_id', models.CharField(max_length=30)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.User')),
            ],
        ),
    ]
