# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_problem_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parallel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Parallel')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='polygon_id',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='lang_id',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='user',
        ),
        migrations.AlterField(
            model_name='submit',
            name='outcome',
            field=models.CharField(choices=[('OK', 'OK'), ('CE', 'Compilation Error'), ('RT', 'Runtime Error'), ('TL', 'Time-Limit Exceeded'), ('PE', 'Presentation Error'), ('WA', 'Wrong Answer'), ('CF', 'Check Failed'), ('PT', 'Partial Solution'), ('AC', 'Accepted for Testing'), ('IG', 'Ignored'), ('DQ', 'Disqualified'), ('PD', 'Pending'), ('ML', 'Memory Limit Exceeded'), ('SE', 'Secutity Violation'), ('SV', 'Style Violation'), ('WT', 'Wall Time Limit Exceeded'), ('PR', 'Pending Review'), ('RJ', 'Rejected'), ('SK', 'Skipped')], max_length=2),
        ),
        migrations.AlterField(
            model_name='submit',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Problem'),
        ),
        migrations.AddField(
            model_name='participation',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.User'),
        ),
        migrations.AddField(
            model_name='contest',
            name='parallel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Parallel'),
        ),
        migrations.AddField(
            model_name='contest',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='contest',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Theme'),
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Contest'),
        ),
        migrations.AddField(
            model_name='problem',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Theme'),
        ),
        migrations.AddField(
            model_name='submit',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Language'),
        ),
        migrations.AddField(
            model_name='submit',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Participation'),
        ),
    ]
