# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_contest_contest_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['season']},
        ),
    ]
