# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20151229_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={},
        ),
    ]
