# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20151229_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={},
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='submit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
