# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20151230_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
