# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20151230_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_id',
            field=models.IntegerField(null=True),
        ),
    ]
