# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_remove_submit_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='submit_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='submit',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
