# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20151230_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='submit_id',
            field=models.IntegerField(null=True),
        ),
    ]
