# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_submit_submit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
