# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20151230_0656'),
        ('stats', '0017_submit_timestamp'),
    ]

    operations = [
    ]
